// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package br.ufc.quixada.calc;


public final class Calculadora {
  private Calculadora() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:br.ufc.quixada.calc.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>double n1 = 2;</code>
     */
    double getN1();

    /**
     * <code>double n2 = 3;</code>
     */
    double getN2();

    /**
     * <code>.br.ufc.quixada.calc.Request.Operacao op = 4;</code>
     */
    int getOpValue();
    /**
     * <code>.br.ufc.quixada.calc.Request.Operacao op = 4;</code>
     */
    br.ufc.quixada.calc.Calculadora.Request.Operacao getOp();
  }
  /**
   * Protobuf type {@code br.ufc.quixada.calc.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:br.ufc.quixada.calc.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      id_ = 0;
      n1_ = 0D;
      n2_ = 0D;
      op_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 17: {

              n1_ = input.readDouble();
              break;
            }
            case 25: {

              n2_ = input.readDouble();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              op_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufc.quixada.calc.Calculadora.internal_static_br_ufc_quixada_calc_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufc.quixada.calc.Calculadora.internal_static_br_ufc_quixada_calc_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufc.quixada.calc.Calculadora.Request.class, br.ufc.quixada.calc.Calculadora.Request.Builder.class);
    }

    /**
     * Protobuf enum {@code br.ufc.quixada.calc.Request.Operacao}
     */
    public enum Operacao
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SOM = 0;</code>
       */
      SOM(0),
      /**
       * <code>SUB = 1;</code>
       */
      SUB(1),
      /**
       * <code>MUL = 2;</code>
       */
      MUL(2),
      /**
       * <code>DIV = 3;</code>
       */
      DIV(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SOM = 0;</code>
       */
      public static final int SOM_VALUE = 0;
      /**
       * <code>SUB = 1;</code>
       */
      public static final int SUB_VALUE = 1;
      /**
       * <code>MUL = 2;</code>
       */
      public static final int MUL_VALUE = 2;
      /**
       * <code>DIV = 3;</code>
       */
      public static final int DIV_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Operacao valueOf(int value) {
        return forNumber(value);
      }

      public static Operacao forNumber(int value) {
        switch (value) {
          case 0: return SOM;
          case 1: return SUB;
          case 2: return MUL;
          case 3: return DIV;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operacao>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Operacao> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operacao>() {
              public Operacao findValueByNumber(int number) {
                return Operacao.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return br.ufc.quixada.calc.Calculadora.Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operacao[] VALUES = values();

      public static Operacao valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Operacao(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:br.ufc.quixada.calc.Request.Operacao)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int N1_FIELD_NUMBER = 2;
    private double n1_;
    /**
     * <code>double n1 = 2;</code>
     */
    public double getN1() {
      return n1_;
    }

    public static final int N2_FIELD_NUMBER = 3;
    private double n2_;
    /**
     * <code>double n2 = 3;</code>
     */
    public double getN2() {
      return n2_;
    }

    public static final int OP_FIELD_NUMBER = 4;
    private int op_;
    /**
     * <code>.br.ufc.quixada.calc.Request.Operacao op = 4;</code>
     */
    public int getOpValue() {
      return op_;
    }
    /**
     * <code>.br.ufc.quixada.calc.Request.Operacao op = 4;</code>
     */
    public br.ufc.quixada.calc.Calculadora.Request.Operacao getOp() {
      br.ufc.quixada.calc.Calculadora.Request.Operacao result = br.ufc.quixada.calc.Calculadora.Request.Operacao.valueOf(op_);
      return result == null ? br.ufc.quixada.calc.Calculadora.Request.Operacao.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (n1_ != 0D) {
        output.writeDouble(2, n1_);
      }
      if (n2_ != 0D) {
        output.writeDouble(3, n2_);
      }
      if (op_ != br.ufc.quixada.calc.Calculadora.Request.Operacao.SOM.getNumber()) {
        output.writeEnum(4, op_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (n1_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, n1_);
      }
      if (n2_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, n2_);
      }
      if (op_ != br.ufc.quixada.calc.Calculadora.Request.Operacao.SOM.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, op_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufc.quixada.calc.Calculadora.Request)) {
        return super.equals(obj);
      }
      br.ufc.quixada.calc.Calculadora.Request other = (br.ufc.quixada.calc.Calculadora.Request) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (
          java.lang.Double.doubleToLongBits(getN1())
          == java.lang.Double.doubleToLongBits(
              other.getN1()));
      result = result && (
          java.lang.Double.doubleToLongBits(getN2())
          == java.lang.Double.doubleToLongBits(
              other.getN2()));
      result = result && op_ == other.op_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + N1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getN1()));
      hash = (37 * hash) + N2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getN2()));
      hash = (37 * hash) + OP_FIELD_NUMBER;
      hash = (53 * hash) + op_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufc.quixada.calc.Calculadora.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufc.quixada.calc.Calculadora.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufc.quixada.calc.Calculadora.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufc.quixada.calc.Calculadora.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufc.quixada.calc.Calculadora.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufc.quixada.calc.Calculadora.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufc.quixada.calc.Calculadora.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufc.quixada.calc.Calculadora.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufc.quixada.calc.Calculadora.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufc.quixada.calc.Calculadora.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufc.quixada.calc.Calculadora.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.ufc.quixada.calc.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:br.ufc.quixada.calc.Request)
        br.ufc.quixada.calc.Calculadora.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufc.quixada.calc.Calculadora.internal_static_br_ufc_quixada_calc_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufc.quixada.calc.Calculadora.internal_static_br_ufc_quixada_calc_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufc.quixada.calc.Calculadora.Request.class, br.ufc.quixada.calc.Calculadora.Request.Builder.class);
      }

      // Construct using br.ufc.quixada.calc.Calculadora.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        n1_ = 0D;

        n2_ = 0D;

        op_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufc.quixada.calc.Calculadora.internal_static_br_ufc_quixada_calc_Request_descriptor;
      }

      public br.ufc.quixada.calc.Calculadora.Request getDefaultInstanceForType() {
        return br.ufc.quixada.calc.Calculadora.Request.getDefaultInstance();
      }

      public br.ufc.quixada.calc.Calculadora.Request build() {
        br.ufc.quixada.calc.Calculadora.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.ufc.quixada.calc.Calculadora.Request buildPartial() {
        br.ufc.quixada.calc.Calculadora.Request result = new br.ufc.quixada.calc.Calculadora.Request(this);
        result.id_ = id_;
        result.n1_ = n1_;
        result.n2_ = n2_;
        result.op_ = op_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufc.quixada.calc.Calculadora.Request) {
          return mergeFrom((br.ufc.quixada.calc.Calculadora.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufc.quixada.calc.Calculadora.Request other) {
        if (other == br.ufc.quixada.calc.Calculadora.Request.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getN1() != 0D) {
          setN1(other.getN1());
        }
        if (other.getN2() != 0D) {
          setN2(other.getN2());
        }
        if (other.op_ != 0) {
          setOpValue(other.getOpValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufc.quixada.calc.Calculadora.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufc.quixada.calc.Calculadora.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private double n1_ ;
      /**
       * <code>double n1 = 2;</code>
       */
      public double getN1() {
        return n1_;
      }
      /**
       * <code>double n1 = 2;</code>
       */
      public Builder setN1(double value) {
        
        n1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double n1 = 2;</code>
       */
      public Builder clearN1() {
        
        n1_ = 0D;
        onChanged();
        return this;
      }

      private double n2_ ;
      /**
       * <code>double n2 = 3;</code>
       */
      public double getN2() {
        return n2_;
      }
      /**
       * <code>double n2 = 3;</code>
       */
      public Builder setN2(double value) {
        
        n2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double n2 = 3;</code>
       */
      public Builder clearN2() {
        
        n2_ = 0D;
        onChanged();
        return this;
      }

      private int op_ = 0;
      /**
       * <code>.br.ufc.quixada.calc.Request.Operacao op = 4;</code>
       */
      public int getOpValue() {
        return op_;
      }
      /**
       * <code>.br.ufc.quixada.calc.Request.Operacao op = 4;</code>
       */
      public Builder setOpValue(int value) {
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.br.ufc.quixada.calc.Request.Operacao op = 4;</code>
       */
      public br.ufc.quixada.calc.Calculadora.Request.Operacao getOp() {
        br.ufc.quixada.calc.Calculadora.Request.Operacao result = br.ufc.quixada.calc.Calculadora.Request.Operacao.valueOf(op_);
        return result == null ? br.ufc.quixada.calc.Calculadora.Request.Operacao.UNRECOGNIZED : result;
      }
      /**
       * <code>.br.ufc.quixada.calc.Request.Operacao op = 4;</code>
       */
      public Builder setOp(br.ufc.quixada.calc.Calculadora.Request.Operacao value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        op_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.br.ufc.quixada.calc.Request.Operacao op = 4;</code>
       */
      public Builder clearOp() {
        
        op_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:br.ufc.quixada.calc.Request)
    }

    // @@protoc_insertion_point(class_scope:br.ufc.quixada.calc.Request)
    private static final br.ufc.quixada.calc.Calculadora.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufc.quixada.calc.Calculadora.Request();
    }

    public static br.ufc.quixada.calc.Calculadora.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public br.ufc.quixada.calc.Calculadora.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:br.ufc.quixada.calc.Reply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>double res = 2;</code>
     */
    double getRes();
  }
  /**
   * Protobuf type {@code br.ufc.quixada.calc.Reply}
   */
  public  static final class Reply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:br.ufc.quixada.calc.Reply)
      ReplyOrBuilder {
    // Use Reply.newBuilder() to construct.
    private Reply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Reply() {
      id_ = 0;
      res_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 17: {

              res_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufc.quixada.calc.Calculadora.internal_static_br_ufc_quixada_calc_Reply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufc.quixada.calc.Calculadora.internal_static_br_ufc_quixada_calc_Reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufc.quixada.calc.Calculadora.Reply.class, br.ufc.quixada.calc.Calculadora.Reply.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int RES_FIELD_NUMBER = 2;
    private double res_;
    /**
     * <code>double res = 2;</code>
     */
    public double getRes() {
      return res_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (res_ != 0D) {
        output.writeDouble(2, res_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (res_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, res_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufc.quixada.calc.Calculadora.Reply)) {
        return super.equals(obj);
      }
      br.ufc.quixada.calc.Calculadora.Reply other = (br.ufc.quixada.calc.Calculadora.Reply) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (
          java.lang.Double.doubleToLongBits(getRes())
          == java.lang.Double.doubleToLongBits(
              other.getRes()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + RES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRes()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufc.quixada.calc.Calculadora.Reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufc.quixada.calc.Calculadora.Reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufc.quixada.calc.Calculadora.Reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufc.quixada.calc.Calculadora.Reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufc.quixada.calc.Calculadora.Reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufc.quixada.calc.Calculadora.Reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufc.quixada.calc.Calculadora.Reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufc.quixada.calc.Calculadora.Reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufc.quixada.calc.Calculadora.Reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufc.quixada.calc.Calculadora.Reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufc.quixada.calc.Calculadora.Reply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.ufc.quixada.calc.Reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:br.ufc.quixada.calc.Reply)
        br.ufc.quixada.calc.Calculadora.ReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufc.quixada.calc.Calculadora.internal_static_br_ufc_quixada_calc_Reply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufc.quixada.calc.Calculadora.internal_static_br_ufc_quixada_calc_Reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufc.quixada.calc.Calculadora.Reply.class, br.ufc.quixada.calc.Calculadora.Reply.Builder.class);
      }

      // Construct using br.ufc.quixada.calc.Calculadora.Reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        res_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufc.quixada.calc.Calculadora.internal_static_br_ufc_quixada_calc_Reply_descriptor;
      }

      public br.ufc.quixada.calc.Calculadora.Reply getDefaultInstanceForType() {
        return br.ufc.quixada.calc.Calculadora.Reply.getDefaultInstance();
      }

      public br.ufc.quixada.calc.Calculadora.Reply build() {
        br.ufc.quixada.calc.Calculadora.Reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.ufc.quixada.calc.Calculadora.Reply buildPartial() {
        br.ufc.quixada.calc.Calculadora.Reply result = new br.ufc.quixada.calc.Calculadora.Reply(this);
        result.id_ = id_;
        result.res_ = res_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufc.quixada.calc.Calculadora.Reply) {
          return mergeFrom((br.ufc.quixada.calc.Calculadora.Reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufc.quixada.calc.Calculadora.Reply other) {
        if (other == br.ufc.quixada.calc.Calculadora.Reply.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getRes() != 0D) {
          setRes(other.getRes());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufc.quixada.calc.Calculadora.Reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufc.quixada.calc.Calculadora.Reply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private double res_ ;
      /**
       * <code>double res = 2;</code>
       */
      public double getRes() {
        return res_;
      }
      /**
       * <code>double res = 2;</code>
       */
      public Builder setRes(double value) {
        
        res_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double res = 2;</code>
       */
      public Builder clearRes() {
        
        res_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:br.ufc.quixada.calc.Reply)
    }

    // @@protoc_insertion_point(class_scope:br.ufc.quixada.calc.Reply)
    private static final br.ufc.quixada.calc.Calculadora.Reply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufc.quixada.calc.Calculadora.Reply();
    }

    public static br.ufc.quixada.calc.Calculadora.Reply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Reply>
        PARSER = new com.google.protobuf.AbstractParser<Reply>() {
      public Reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Reply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Reply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Reply> getParserForType() {
      return PARSER;
    }

    public br.ufc.quixada.calc.Calculadora.Reply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_quixada_calc_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_br_ufc_quixada_calc_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_quixada_calc_Reply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_br_ufc_quixada_calc_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\023br.ufc.quixada.calc\"\220\001\n" +
      "\007Request\022\n\n\002id\030\001 \001(\005\022\n\n\002n1\030\002 \001(\001\022\n\n\002n2\030\003" +
      " \001(\001\0221\n\002op\030\004 \001(\0162%.br.ufc.quixada.calc.R" +
      "equest.Operacao\".\n\010Operacao\022\007\n\003SOM\020\000\022\007\n\003" +
      "SUB\020\001\022\007\n\003MUL\020\002\022\007\n\003DIV\020\003\" \n\005Reply\022\n\n\002id\030\001" +
      " \001(\005\022\013\n\003res\030\002 \001(\001B\"\n\023br.ufc.quixada.calc" +
      "B\013Calculadorab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_br_ufc_quixada_calc_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_br_ufc_quixada_calc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_br_ufc_quixada_calc_Request_descriptor,
        new java.lang.String[] { "Id", "N1", "N2", "Op", });
    internal_static_br_ufc_quixada_calc_Reply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_br_ufc_quixada_calc_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_br_ufc_quixada_calc_Reply_descriptor,
        new java.lang.String[] { "Id", "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
